### ISSUE TITLE
load pretrained net

### ISSUE THREAD

**Issue by dataintensiveapplication** [antspy/inception_v1.pytorch#2]
Hi, I downloaded the weights file from the link, but it's a .dms and I am not able to load or import it in pytorch, can you give a small example of how to load the weights of the net?

**Comment by antspy** [comment]
Hi, 

You simply have to load them like 

`model.load_state_dict(torch.load(path_to_weights))`

You can also use the inception_v1_pretrained  function in the main file; you just need to provide a path to were you saved the weights

```python
def inception_v1_pretrained(path_to_weights='default'):
    model = Inception_v1(num_classes=1000)
    if path_to_weights.lower() == 'default':
        _currDir = os.path.dirname(os.path.abspath(__file__))
        path_to_weights = os.path.join(_currDir, 'inception_v1_weights')
    model.load_state_dict(torch.load(path_to_weights))
    return model
```

**Comment by dataintensiveapplication** [comment]
you're right. I was had to change the default name adding the extension. 
It works, thank you
